core/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('',views.index),
    path('login/',views.signin,name = "login"),
    path('register/',views.register,name = "register"),
    path('property/<int:id>/',views.propertyDetail,name = "propertyDetail" ),
    path('contactOwner/',views.contact_owner,name ="contactOwner" ),
    path('messages/',views.message,name = "messages"),
    path('message/<int:pk>',views.messageDetail,name = "messageDetail"),
    path('logout/', views.logout_view, name='logout'),
    path('properties/new/', views.property_create, name='property_create'),
    path('properties/<int:pk>/edit/', views.property_update, name='property_update'),
    path('properties/<int:pk>/delete/', views.property_delete, name='property_delete'),
    path('propertyList/',views.propertyList,name = "propertyList"),
    path('bookproperty/',views.bookproperty,name = "bookproperty"),
    path('orderlist/',views.orderlist,name = "orderlist"),
    path('aboutus/',views.aboutus,name = "aboutus"),
    path('update-profile/', views.update_profile, name='update_profile'),
    path('dashboardListing/',views.dashboardPropertyListing,name = "dashboardProductListing"),
    path('adminorderlist/',views.adminorderlist,name = "adminorderlisting"),
    path('adminmanageproperty/',views.adminpropertyList,name = "adminpropertyList")




]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Property(models.Model):
    owner = models.ForeignKey(User,on_delete = models.CASCADE)
    title = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    description = models.TextField() 
    price = models.DecimalField(max_digits=10, decimal_places=2)
    bedrooms = models.PositiveIntegerField()
    bathrooms = models.PositiveIntegerField()
    image = models.ImageField(upload_to='img',null=True,blank=True)
    available_for_rent = models.BooleanField(default=False)
    is_approved = models.BooleanField(default = False)

    def __str__(self):
        return self.title
    
class Contact(models.Model):
    owner = models.ForeignKey(User,on_delete = models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    contact_number = models.CharField(max_length=20)
    message = models.TextField()

    def __str__(self):
        return self.name
    


class BookProperty(models.Model): 
    owner = models.ForeignKey(User,on_delete = models.CASCADE,related_name = "owner")
    renter = models.ForeignKey(User,on_delete = models.CASCADE,related_name = "renter")
    property = models.ForeignKey(Property,on_delete = models.CASCADE)
    renter_phone =models.CharField(max_length = 200,null = True,blank = True)

    # def __str__(self): 
    #     return f"{self.owner.username}-{self.renter.username}-{self.property.title}"
    
    
class Phone(models.Model): 
    user = models.OneToOneField(User,on_delete= models.CASCADE)
    phone = models.CharField(max_length = 200)
    
    def __str__(self): 
        return f"{self.user.username}-{self.phone}"

templates/RegisterProperty.html
{% extends 'base.html' %}

{% block content %}
<style>
    /* Add your custom styles here */
    #id_title,
    #id_description,
    #id_location,
    #id_price,
    #id_bedrooms,
    #id_bathrooms,
    #id_image {
        /* Common styles for input fields */
        width: calc(100% - 1rem); /* Reduce width */
        padding: 0.25rem; /* Reduce padding */
        margin-bottom: 0.125rem; /* Adjust margin */
        border: 1px solid #ccc;
        border-radius: 0.125rem;
        outline: none;
        transition: border-color 0.3s;
        font-size: 0.75rem; /* Reduce font size */
    }

    #id_available_for_rent {
        /* Styles for the available_for_rent checkbox */
        margin-right: 0.125rem; /* Adjust margin */
        /* Add more styles as needed */
    }

    #messages-container {
        /* Styles for the messages container */
        /* Add styles here */
    }

    /* Adjust the button size */
    button {
        font-size: 0.875rem;
        padding: 0.5rem;
        margin-top: 0.25rem;
    }
</style>

<div class="min-h-screen flex justify-center items-center">
    <div class="bg-white p-2 rounded-lg shadow-lg max-w-md w-full">
        <h2 class="text-xl font-bold mb-2">Add Property</h2>
        {% if messages %}
        <div id="messages-container" class="p-1 text-center">
            {% for msg in messages %}
            <div class="bg-green-500 text-white p-1 rounded-md mb-1">
                <span>{{ msg.message }}</span>
                <button onclick="closeMessage(this)" class="ml-1 text-white">x</button>
            </div>
            {% endfor %}
        </div>

        <script>
            function closeMessage(button) {
                var messageContainer = button.parentElement;
                messageContainer.style.display = 'none';
            }

            // Automatically hide messages after 3 seconds
            setTimeout(function () {
                var messagesContainer = document.getElementById('messages-container');
                if (messagesContainer) {
                    messagesContainer.style.display = 'none';
                }
            }, 5000);
        </script>
        {% endif %}
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="mb-1">
                <label for="id_title" class="block text-gray-700 text-xs font-bold mb-0.5">Title</label>
                {{ form.title }}
            </div>
            <div class="mb-1">
                <label for="id_location" class="block text-gray-700 text-xs font-bold mb-0.5">Location</label>
                {{ form.location }}
            </div>
            <div class="mb-1">
                <label for="id_price" class="block text-gray-700 text-xs font-bold mb-0.5">Price</label>
                {{ form.price }}
            </div>


            <div class="mb-1">
                <label for="id_description" class="block text-gray-700 text-xs font-bold mb-0.5">Description</label>
                {{ form.description }}
            </div>

            

           
            <div class="mb-1">
                <label for="id_bedrooms" class="block text-gray-700 text-xs font-bold mb-0.5">Bedrooms</label>
                {{ form.bedrooms }}
            </div>

            <div class="mb-1">
                <label for="id_bathrooms" class="block text-gray-700 text-xs font-bold mb-0.5">Bathrooms</label>
                {{ form.bathrooms }}
            </div>

            <div class="mb-1">
                <label for="id_image" class="block text-gray-700 text-xs font-bold mb-0.5">Image URL</label>
                {{ form.image }}
            </div>

            <div class="mb-1">
                <label for="id_available_for_rent" class="flex items-center">
                    {{ form.available_for_rent }}
                    <span class="text-gray-700 text-xs font-bold">Available for rent</span>
                </label>
            </div>

            <button type="submit"
                class="w-full bg-blue-500 text-white py-2 rounded-lg hover:bg-blue-600 transition duration-300">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

templates/admindashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Dashboard</title>
    <!-- Include Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">
    <!-- Sidebar -->
    <div class="flex h-screen">
        <div class="w-64 bg-gray-800 text-white flex flex-col">
            <div class="p-4">
                <a href="/" class="font-bold text-2xl text-center mb-5">Home Rental</a>
                <h1 class="text-xl font-semibold mt-5   ">Admin Dashboard</h1>
            </div>
            <ul class="flex-1">
                <li class="p-4 hover:bg-gray-700 cursor-pointer"><a href="{%url 'dashboardProductListing' %}">Properties requests</a></li>
                <li class="p-4 hover:bg-gray-700 cursor-pointer"><a href="{%url 'adminorderlisting' %}">Order Lists</a></li>
                <li class="p-4 hover:bg-gray-700 cursor-pointer"><a href="{%url 'adminpropertyList' %}">Manage Property</a></li>


            </ul>
        </div>
        <!-- Main Content -->
        {%block content%}
        {%endblock content%}
        
    </div>
</body>
</html>

templates/adminmanageproperty.html
{%extends 'admindashboard.html'%}
{%block content%}
<div class="flex-1 p-8">
    <h2 class="text-2xl font-semibold mb-4">Properties Listing</h2>
               
    {% if messages %}
    <div id="messages-container" class="p-4 text-center">
      {% for msg in messages %}
        <div class="bg-green-500 text-white p-2 rounded-md mb-4">
          <span>{{ msg.message }}</span>
          <button onclick="closeMessage(this)" class="ml-2 text-white">x</button>
        </div>
      {% endfor %}
    </div>
  
    <script>
      function closeMessage(button) {
        var messageContainer = button.parentElement;
        messageContainer.style.display = 'none';
      }
  
      // Automatically hide messages after 3 seconds
      setTimeout(function () {
        var messagesContainer = document.getElementById('messages-container');
        if (messagesContainer) {
          messagesContainer.style.display = 'none';
        }
      }, 5000);
    </script>
  {% endif %}
    <div class="overflow-x-auto">
        <table class="min-w-full bg-white">
            <thead class="bg-gray-200">
                <tr>
                    <th class="py-2 px-4 border-b ">Id</th>
                    <th class="py-2 px-4 border-b ">Title</th>
                    <th class="py-2 px-4 border-b ">Status</th>
    
    
                    
                </tr>
            </thead>
            <tbody class="divide-y divide-gray-200">
                {%for property in properties%}
                        <tr>
                            <td class="py-2 px-4 border-b text-center">{{property.id}}</td>
                            <td class="py-2 px-4 border-b text-center">{{property.title}}</td>
                            <td class="py-2 px-4 border-b text-center">{{property.is_approved}}</td>

                            <td class="py-2 px-4 border-b text-center">
                                <a  href = "{%url 'property_update' property.pk%}" class="bg-blue-500 text-white px-2 py-1 rounded">Update</a>
                                <a  href = "{%url 'property_delete' property.pk%}" class="bg-red-500 text-white px-2 py-1 rounded">delete</a>
                            </td>
                        </tr>
            {%endfor%}

                <!-- Add more rows as needed -->
            </tbody>
        </table>
        <div class="flex justify-center mt-4">
            {% if properties.has_previous %}
            <a href="?page=1" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4 rounded-l">
                First
            </a>
            <a href="?page={{ properties.previous_page_number }}" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4">
                Previous
            </a>
            {% endif %}
            {% if properties.has_next %}
            <a href="?page={{ properties.next_page_number }}" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4">
                Next
            </a>
            <a href="?page={{ properties.paginator.num_pages }}" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4 rounded-r">
                Last
            </a>
            {% endif %}
        </div>
    </div>
</div>
{%endblock content%}

templates/adminorderlist.html
{%extends 'admindashboard.html'%}
{%block content%}
<div class="flex-1 p-8">
    <h2 class="text-2xl font-semibold mb-4">Properties Listing</h2>
               
    {% if messages %}
    <div id="messages-container" class="p-4 text-center">
      {% for msg in messages %}
        <div class="bg-green-500 text-white p-2 rounded-md mb-4">
          <span>{{ msg.message }}</span>
          <button onclick="closeMessage(this)" class="ml-2 text-white">x</button>
        </div>
      {% endfor %}
    </div>
  
    <script>
      function closeMessage(button) {
        var messageContainer = button.parentElement;
        messageContainer.style.display = 'none';
      }
  
      // Automatically hide messages after 3 seconds
      setTimeout(function () {
        var messagesContainer = document.getElementById('messages-container');
        if (messagesContainer) {
          messagesContainer.style.display = 'none';
        }
      }, 5000);
    </script>
  {% endif %}
    <div class="overflow-x-auto">
        <table class="min-w-full bg-white">
            <thead class="bg-gray-200">
                <tr>

                    <th class="py-2 px-4 border-b ">Property</th>
                    <th class="py-2 px-4 border-b ">owner</th>
                    <th class="py-2 px-4 border-b ">renter</th>
                    <th class="py-2 px-4 border-b ">renter's contact</th>

                </tr>
            </thead>
            <tbody class="divide-y divide-gray-200">
                {%for order in orders%}
                <tr>
                    <tr>
                        <td class="py-2 px-4 border-b text-center">{{order.property.title}}</td>
                        <td class="py-2 px-4 border-b text-center">{{order.owner}}</td>
                        <td class="py-2 px-4 border-b text-center">{{order.renter}}</td>
                        <td class="py-2 px-4 border-b text-center">
                            {{order.renter_phone}}
                        </td>
                    </tr>
                </tr>
                {%endfor%}

                <!-- Add more rows as needed -->
            </tbody>
        </table>
        <div class="flex justify-center mt-4">
            {% if orders.has_previous %}
            <a href="?page=1" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4 rounded-l">
                First
            </a>
            <a href="?page={{ orders.previous_page_number }}" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4">
                Previous
            </a>
            {% endif %}
            {% if orders.has_next %}
            <a href="?page={{ orders.next_page_number }}" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4">
                Next
            </a>
            <a href="?page={{ orders.paginator.num_pages }}" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4 rounded-r">
                Last
            </a>
            {% endif %}
        </div>
    
    </div>
</div>
{%endblock content%}

templates/base.html
{%load static%}
<!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Rental System</title>
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    </head>

    <body class="bg-gray-100 flex   flex-col " style = "height : 100vh">
        <!-- Navbar -->
        <nav class="bg-gray-800 text-white p-4">
            <div class="container mx-auto flex justify-between items-center">
                <a  href = "/" class=" cursor-pointer text-2xl font-bold border p-6 rounded-xl border-gray-300"><img src="{%static 'logo.png'%}" alt="" style = "width: 100px;"></a>
                <div class="hidden md:block">
                    <a href="/" class="px-4">Home</a>
                    <a href="/aboutus/" class="px-4">Contact Us</a>

                    {%if request.user.is_authenticated%}
                    <a href="{%url 'property_create'%}" class="px-4">Add Property</a>
                    <a href="/messages/" class="px-4">Views messages</a>
                    {%if not request.user.is_superuser%}
                    <a href="/propertyList/" class="px-4">Manage Property</a>
                    <a href="/orderlist/" class="px-4">OrderList</a>
                    {%endif%}
                    <a href="/update-profile/" class="px-4">Update Profiles</a>
                    {%if request.user.is_superuser%}
                    <a href="/dashboardListing/" class="px-4">dashboard</a>
        
                    {%endif%}
                    
                    

                    <a href="/logout/" class="px-4">logout</a>
                    
                    {%else%}
                    
                    <a href="/login/" class="px-4">login</a>
                    <a href="/register/" class="px-4">register</a>
                    {%endif%}
                </div>
                <div class="md:hidden">
                    <!-- Mobile menu button -->
                    <button id="mobile-menu-button"
                        class="focus:outline-none flex items-center px-3 py-2 border rounded text-white border-white hover:text-gray-200 hover:border-white">
                        <svg class="h-3 w-3" viewBox="0 0 20 20" fill="currentColor">
                            <path fill-rule="evenodd"
                                d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 6a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zm0 6a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                                clip-rule="evenodd" />
                        </svg>
                    </button>
                </div>
            </div>
        </nav>

        <!-- Mobile menu -->
        <div id="mobile-menu"
            class="md:hidden bg-gray-800 text-white py-2 px-4 mt-2 rounded-lg shadow-lg text-center hidden">
            <a href="#" class="block py-2">Home</a>
            <a href="#" class="block py-2">About</a>
            {%if request.user.is_authenticated%}
            <a href="{%url 'property_create'%}" class="px-4">Add Property</a>
            <a href="/messages/" class="px-4">Views messages</a>
            {%if not request.user.is_superuser%}
            <a href="/propertyList/" class="px-4">Manage Property</a>
            <a href="/orderlist/" class="px-4">OrderList</a>
            {%endif%}
            <a href="/update-profile/" class="px-4">Update Profiles</a>
            {%if request.user.is_superuser%}
            <a href="/dashboardListing/" class="px-4">dashboard</a>

            {%endif%}
            

            <a href="/logout/" class="px-4">logout</a>
            
            {%else%}
            
            <a href="/login/" class="px-4">login</a>
            <a href="/register/" class="px-4">register</a>
            {%endif%}   
        </div>

        {%block content%}
        {%endblock content%}        
        <footer class="bg-gray-800 text-white py-8 mt-auto">
            <div class="container mx-auto text-center">
                <p>&copy; 2024 Home Rental System. All rights reserved.</p>
            </div>
        </footer>   

        <script>
            // Mobile menu toggle
            document.getElementById('mobile-menu-button').addEventListener('click', function () {
                var mobileMenu = document.getElementById('mobile-menu');
                if (mobileMenu.classList.contains('hidden')) {
                    mobileMenu.classList.remove('hidden');
                } else {
                    mobileMenu.classList.add('hidden');
                }
            });
        </script>
    </body>

    </html>

templates/index.html
{%extends 'base.html'%}

{%block content%}
<div class="bg-gray-900 text-white py-20">
    <div class="container mx-auto text-center">
        <h1 class="text-4xl md:text-6xl font-bold mb-4">Welcome to Home Rental Service</h1>
        <p class="text-lg md:text-xl mb-8">Find Your Perfect Cuddle Spot</p>
        <form class="mx-auto flex gap- 3 max-w-lg" method = "get" action = "/">
            <input type="text"
                class="w-full px-4 py-3 rounded-full bg-gray-800 focus:outline-none focus:shadow-outline text-white"
                placeholder="Search..." name = "search">
                <button class="bg-yellow-500 p-3 rounded-full ml-3 text-white ">Search</button>
        </form>
    </div>
</div>

<!-- News Section -->
<div class="container mx-auto mb-12 mt-12">
    
    <h2 class="text-3xl font-bold mb-8">Rentals</h2>
    {% if messages %}
    <div id="messages-container" class="p-4 text-center">
      {% for msg in messages %}
        <div class="bg-green-500 text-white p-2 rounded-md mb-4">
          <span>{{ msg.message }}</span>
          <button onclick="closeMessage(this)" class="ml-2 text-white">x</button>
        </div>
      {% endfor %}
    </div>
  
    <script>
      function closeMessage(button) {
        var messageContainer = button.parentElement;
        messageContainer.style.display = 'none';
      }
  
      // Automatically hide messages after 3 seconds
      setTimeout(function () {
        var messagesContainer = document.getElementById('messages-container');
        if (messagesContainer) {
          messagesContainer.style.display = 'none';
        }
      }, 5000);
    </script>
  {% endif %}

    {%if properties%}
    <div class="container w-full h-auto mb-3">
      <form id="filterForm" action="/" class="flex sm:flex-row flex-col justify-center gap-3 items-center" method="get">
          <div class="flex gap-1 flex-col items-center">
              <label for="startdate" class="font-bold">From</label>
              <input type="Number" id="from" placeholder="price" class="p-2 px-5 bg-gray-200 border-1 rounded-xl border-gray-300" name="from" value="{{ request.GET.from }}">
          </div>
          <div class="flex gap-1 flex-col items-center">
              <label for="enddate" class="font-bold">To</label>
              <input type="number" id="enddate"placeholder="price" class="p-2 px-5 bg-gray-200 border-1 rounded-xl border-gray-300" name="to" value="{{ request.GET.to }}">
          </div>
          
          <div class="flex gap-1 flex-col items-center">
              <label for="searchUser" class="font-bold">Search location</label>

              <input type="text" id="searchUser" placeholder="Search Location" class="p-2 px-5 bg-gray-200 border-1 rounded-xl border-gray-300" name="location" value="{{ request.GET.locations }}">
          </div>
         
          <button class="bg-indigo-500 mt-4 p-2 pl-5 rounded-lg hover:bg-indigo-700 text-white">Filter Rentals</button>

      </form>
  </div>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <!-- News Card 1 -->
        {%for property in properties%}
        <div class="bg-white rounded-lg p-6 shadow-lg overflow-hidden">
          {% if property.image %}
          <img src="{{property.image.url}}" alt="News" class="w-full h-64 object-cover" >
          {% else %}
                <img src="# alt="Property Image" class="w-full h-auto rounded-t-lg">
                {% endif %}
            
            <div class="p-6">
                <h3 class="text-xl font-bold mb-2">{{property}}</h3>
                <p class="text-gray-700 mt-2 font-bold">Location: {{property.location}}</p>
                <p class="text-gray-700 mt-2 font-bold">price : {{property.price}}</p>
                
            </div>
            <a href="{%url 'propertyDetail' property.id%}" class="p-3 bg-green-500 rounded-xl text-white ml-5 shadow-md mb-3">View Detail</a>
        </div>
        {%endfor%}


    </div>
    {%else%}
    <h1 class="text-center font-bold text-red-500 text-2xl">No rental available</h1>
    {%endif%}
    <div class="flex justify-center mt-4">
      {% if properties.has_previous %}
      <a href="?page=1" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4 rounded-l">
          First
      </a>
      <a href="?page={{ properties.previous_page_number }}" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4">
          Previous
      </a>
      {% endif %}
      <span class="bg-gray-200 text-gray-700 font-semibold py-2 px-4">{{ properties.number }}</span>
      {% if properties.has_next %}
      <a href="?page={{ properties.next_page_number }}" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4">
          Next
      </a>
      <a href="?page={{ properties.paginator.num_pages }}" class="bg-gray-200 hover:bg-gray-300 text-gray-700 font-semibold py-2 px-4 rounded-r">
          Last
      </a>
      {% endif %}
  </div>
</div>
{%endblock content%}

templates/login.html
{%extends 'base.html'%}
{%load static%}
    <!-- Login Section -->
    {%block content%}
    <div class="flex justify-center items-center h-screen">
        <div class="bg-white rounded-lg p-10 max-w-md w-full shadow-md">
           
            {% if messages %}
            <div id="messages-container" class="p-4 text-center">
              {% for msg in messages %}
                <div class="bg-red-500 text-white p-2 rounded-md mb-4">
                  <span>{{ msg.message }}</span>
                  <button onclick="closeMessage(this)" class="ml-2 text-white">x</button>
                </div>
              {% endfor %}
            </div>
          
            <script>
              function closeMessage(button) {
                var messageContainer = button.parentElement;
                messageContainer.style.display = 'none';
              }
          
              // Automatically hide messages after 3 seconds
              setTimeout(function () {
                var messagesContainer = document.getElementById('messages-container');
                if (messagesContainer) {
                  messagesContainer.style.display = 'none';
                }
              }, 5000);
            </script>
          {% endif %}
            <div class="text-center mb-8">
              <img src="{%static 'logo.png'%}" alt="Logo" class="mx-auto mb-4 rounded-full border-4 border-white" style="width:150px ">
              <h1 class = "text-center font-bold text-gray-800">Home Rental</h1>              </div>
            <form method = "post">
                {%csrf_token%}
                
                <div class="mb-4">
                    <label for="email" class="block text-sm font-medium text-gray-700">Usernames</label>
                    <input type="text" id="email" name="username"
                        class="w-full px-3 py-2 rounded-lg bg-gray-100 focus:outline-none focus:ring focus:border-blue-300">
                </div>
                <div class="mb-6">
                    <label for="password" class="block text-sm font-medium text-gray-700">Password</label>
                    <input type="password" id="password" name="password"
                        class="w-full px-3 py-2 rounded-lg bg-gray-100 focus:outline-none focus:ring focus:border-blue-300">
                </div>
                <button type="submit"
                    class="w-full bg-blue-600 text-white py-2 rounded-lg hover:bg-blue-700 transition duration-300">Login</button>
            </form>
        </div>
    </div>

    <script>
        // Mobile menu toggle
        document.getElementById('mobile-menu-button').addEventListener('click', function () {
            var mobileMenu = document.getElementById('mobile-menu');
            if (mobileMenu.classList.contains('hidden')) {
                mobileMenu.classList.remove('hidden');
            } else {
                mobileMenu.classList.add('hidden');
            }
        });
    </script>
    {%endblock content%}

templates/messageDetail.html
{%extends 'base.html'%}

{%block content%}
<div class="container mx-auto p-4">
    <div class="bg-white rounded-lg shadow-lg p-8 max-w-md mx-auto">
        <h2 class="text-2xl font-bold mb-4">Message Details</h2>

        <!-- Message Card -->
        <div class="bg-gray-100 p-4 rounded-lg mb-4">
            
            <div class="mb-2">
                <span class="font-bold">Email:</span> {{message.email}}
            </div>
            <div class="mb-2">
                <span class="font-bold">Phone:</span>{{message.contact_number}}
            </div>
            <div class="mb-2">
                <span class="font-bold">Message:</span> {{message.message}}
            </div>
        </div>

        <!-- Back Button -->
        <a href="/messages/" class="text-blue-500 hover:underline">Back to Inbox</a>
    </div>
</div>

{%endblock content%}

templates/orderlist.html
{%extends 'base.html'%}
{%block content%}

<div class="overflow-x-auto p-10">
    <table class="  min-w-full bg-white border border-gray-300">
        <thead>
            <tr>
                <th class="py-2 px-4 border-b ">Property</th>
                <th class="py-2 px-4 border-b ">owner</th>
                <th class="py-2 px-4 border-b ">renter</th>
                <th class="py-2 px-4 border-b ">renter's contact</th>


            </tr>
        </thead>
        <tbody>
            {%for order in orders%}
            <tr>
                <td class="py-2 px-4 border-b text-center">{{order.property.title}}</td>
                <td class="py-2 px-4 border-b text-center">{{order.owner}}</td>
                <td class="py-2 px-4 border-b text-center">{{order.renter}}</td>
                <td class="py-2 px-4 border-b text-center">
                    {{order.renter_phone}}
                </td>
            </tr>
            {%endfor%}
           
        </tbody>
    </table>
</div>

{%endblock content%}

templates/viewMessage.html
{%extends 'base.html'%}
{%block content%}

<div class="overflow-x-auto p-10">
    <table class="  min-w-full bg-white border border-gray-300">
        <thead>
            <tr>
                <th class="py-2 px-4 border-b ">Email</th>
                <th class="py-2 px-4 border-b ">Contact</th>
                <th class="py-2 px-4 border-b ">Message</th>
                <th class="py-2 px-4 border-b ">Actions</th>
            </tr>
        </thead>
        <tbody>
            {%for message in messages%}
            <tr>
                <td class="py-2 px-4 border-b text-center">{{message.email}}</td>
                <td class="py-2 px-4 border-b text-center">{{message.contact_number}}</td>
                <td class="py-2 px-4 border-b text-center">{{message.message|slice:20}}</td>
                <td class="py-2 px-4 border-b text-center">
                    <a  href = "{%url 'messageDetail' message.pk%}" class="bg-blue-500 text-white px-2 py-1 rounded">view message</a>
                </td>
            </tr>
            {%endfor%}
           
        </tbody>
    </table>
</div>

{%endblock content%}